name: Brew

on:
  push:
    branches: [ "brew_test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - name: Release project to Homebrew tap
        uses: Justintime50/homebrew-releaser@v3
        with:
          # The name of the homebrew tap to publish your formula to as it appears on GitHub (Homebrew taps must start with `homebrew-`).
          # Required - strings
          homebrew_owner: shloop
          homebrew_tap: homebrew-tap

          # The Personal Access Token (saved as a repo secret) that has `repo` permissions for the repo running the action AND Homebrew tap you want to release to.
          # Required - string
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

          # Install command for your formula.
          # Required - string
          install: 'bin.install gbscraper'
