name: Choco

on: 
  push:
    branches: 
      - choco_upload

env:
  GH_TOKEN: ${{ github.token }}
  API_KEY: ${{ secrets.CHOCO_API_KEY }}

jobs:
  test:
    name: Choco pkg
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - name: Package
      env:
        VERSION: 0.3.8
      run: |
        mkdir dist
        gh release download v$env:VERSION --pattern '*.zip' -D dist
        $z32 = "google-book-scraper-$env:VERSION-windows-x86-portable.zip"
        $z64 = "google-book-scraper-$env:VERSION-windows-x64-portable.zip"
        mv dist/$z32 pkg/choco/tools
        mv dist/$z64 pkg/choco/tools
        cd pkg/choco
        (Get-Content gbscraper.nuspec).Replace('$VERSION', $env:VERSION) | Set-Content gbscraper.nuspec
        (Get-Content tools/chocolateyinstall.ps1).Replace('$VERSION', $env:VERSION) | Set-Content tools/chocolateyinstall.ps1
        choco pack
        choco install gbscraper -s . -y
        choco apikey --key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/
        choco push gbscraper.$env:VERSION.nupkg --source https://push.chocolatey.org/
