name: Publish
description: Publish to various code registries/package managers

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:

  get_release_version:
    name: Get release version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      tag: ${{ steps.get_version.outputs.tag }}
    steps:
      - name: Determine latest version
        id: latest_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
      - name: Get current version
        id: get_version
        env:
          # Get version from current release if workflow was triggered by release, otherwise use latest release version
          TAG: ${{ github.event.release.tag_name || steps.latest_version.outputs.release  }}
        run: |
          # Get version without preceding 'v'
          VERSION=${TAG#v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

  publish_crate:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    # environment: release  # Optional: for enhanced security
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Authorize with crates.io
        id: auth
        uses: rust-lang/crates-io-auth-action@v1
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  publish_homebrew:
    name: Publish to brew tap
    runs-on: ubuntu-latest
    steps:
      - name: Release project to Homebrew tap
        uses: Justintime50/homebrew-releaser@v3
        with:
          homebrew_owner: shloop
          homebrew_tap: homebrew-tap
          github_token: ${{ secrets.TAP_TOKEN }}
          target_darwin_amd64: true
          target_darwin_arm64: true
          target_linux_amd64: true
          target_linux_arm64: true
          install: 'bin.install "gbscraper"'
          update_readme_table: true

  publish_winget:
    name: Publish to WinGet
    needs: get_release_version
    runs-on: ubuntu-slim
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: shloop.gbscraper
          installers-regex: '\.exe$' # Only .exe files
          token: ${{ secrets.WINGET_TOKEN }}
          version: ${{ needs.get_release_version.outputs.version }}

  publish_choco:
    name: Publish to Chocolatey
    needs: get_release_version
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Package and upload to Chocolatey
        env:
          VERSION: ${{ needs.get_release_version.outputs.version }}
        run: |
          $VERSION = ${{ needs.get_release_version.outputs.version }}
          $TAG = ${{ needs.get_release_version.outputs.tag }}

          # Download portable binaries from release and place in tools directory
          mkdir dist
          gh release download $TAG --pattern '*.zip' -D dist
          $z32 = "google-book-scraper-$VERSION-windows-x86-portable.zip"
          $z64 = "google-book-scraper-$VERSION-windows-x64-portable.zip"
          mv dist/$z32 pkg/choco/tools
          mv dist/$z64 pkg/choco/tools

          # Generate combined license file
          $lcns = "pkg/choco/tools/LICENSE.txt"
          echo "This software is licensed under the MIT and Apache-2.0 licenses, which are contained below" > $lcns
          echo "The licenses for the libraries used by this software can be found in attribution.txt" >> $lcns
          echo "" >> $lcns
          echo "=== MIT License ===" >> $lcns
          echo "" >> $lcns
          cat LICENSE-MIT >> $lcns
          echo "" >> $lcns
          echo "=== Apache-2.0 License ===" >> $lcns
          echo "" >> $lcns
          cat LICENSE-APACHE >> $lcns

          # Configure files for this version
          cd pkg/choco
          (Get-Content gbscraper.nuspec).Replace('$VERSION', $VERSION) | Set-Content gbscraper.nuspec
          (Get-Content tools/chocolateyinstall.ps1).Replace('$VERSION', $VERSION) | Set-Content tools/chocolateyinstall.ps1

          # Package
          choco pack

          # Test installation
          choco install gbscraper -s . -y

          # Push
          choco apikey --key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/
          choco push gbscraper.$VERSION.nupkg --source https://push.chocolatey.org/