name: Publish
description: Publish to various code registries/package managers

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:

  publish_crate:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    # environment: release  # Optional: for enhanced security
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v6
    - uses: rust-lang/crates-io-auth-action@v1
      id: auth
    - run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  publish_homebrew:
    name: Publish to brew tap
    runs-on: ubuntu-latest
    steps:
      - name: Release project to Homebrew tap
        uses: Justintime50/homebrew-releaser@v3
        with:
          homebrew_owner: shloop
          homebrew_tap: homebrew-tap
          github_token: ${{ secrets.TAP_TOKEN }}
          target_darwin_amd64: true
          target_darwin_arm64: true
          target_linux_amd64: true
          target_linux_arm64: true
          install: 'bin.install "gbscraper"'
          update_readme_table: true

  publish_winget:
    name: Publish to WinGet
    runs-on: ubuntu-slim
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: shloop.gbscraper
          installers-regex: '\.exe$' # Only .exe files
          token: ${{ secrets.WINGET_TOKEN }}

  publish_choco:
    name: Publish to Chocolatey
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - name: Package
      run: |
        $VERSION = "${{ github.event.release.tag_name }}".SubString(1)
        mkdir dist
        gh release download v$VERSION --pattern '*.zip' -D dist
        $z32 = "google-book-scraper-$VERSION-windows-x86-portable.zip"
        $z64 = "google-book-scraper-$VERSION-windows-x64-portable.zip"
        mv dist/$z32 pkg/choco/tools
        mv dist/$z64 pkg/choco/tools
        cd pkg/choco
        (Get-Content gbscraper.nuspec).Replace('$VERSION', $VERSION) | Set-Content gbscraper.nuspec
        (Get-Content tools/chocolateyinstall.ps1).Replace('$VERSION', $VERSION) | Set-Content tools/chocolateyinstall.ps1
        choco pack
        choco install gbscraper -s . -y
        choco apikey --key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/
        choco push gbscraper.$VERSION.nupkg --source https://push.chocolatey.org/