name: Rebuild installers

on:
  push:
    branches: [ "winget_troubleshooting" ]

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}
  VERSION: 0.4.0

permissions:
  contents: write

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-slim
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Set version
        id: set_version
        run: |
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  build_installers:
    name: Rebuild installers
    needs: setup
    strategy:
      matrix:
        platform: 
          # - name: Windows-i686
          #   arch: x86compatible
          #   runs_on: windows-latest
          #   target: i686-pc-windows-msvc
          #   filename: google-book-scraper-${{ needs.setup.outputs.version }}-windows-x86
          # - name: Windows-x86_64
          #   arch: x64compatible
          #   runs_on: windows-latest
          #   target: x86_64-pc-windows-msvc
          #   filename: google-book-scraper-${{ needs.setup.outputs.version }}-windows-x64
          - name: Windows-aarch64
            arch: arm64
            runs_on: windows-11-arm
            target: aarch64-pc-windows-msvc
            filename: google-book-scraper-${{ needs.setup.outputs.version }}-windows-arm64

    env:
      ARCH: ${{ matrix.platform.arch }}
      TAG: v${{ needs.setup.outputs.version }}
      INSTALLER_BASE: ${{ matrix.platform.filename }}-installer
      # INSTALLER_EXE: ${{ matrix.platform.filename }}-installer.exe
      PORTABLE_ZIP: ${{ matrix.platform.filename }}-portable.zip

    runs-on: ${{ matrix.platform.runs_on }}
    steps:
    
    - name: winget install test
      run: |
        Install-Module -Name Microsoft.WinGet.Client -Repository PSGallery -Force
        Repair-WinGetPackageManager -Latest -Force
        winget install shloop.gbscraper

    - name: Outputs
      id: env
      run: |
        echo "installer_exe=${{ matrix.platform.filename }}-installer.exe" >> $GITHUB_OUTPUT

    - name: Test current installer
      run: |
        gh release download -R shloop/google-book-scraper $Env:TAG -p google-book-scraper-0.4.0-windows-arm64-installer.exe
        ls
        echo "please print: ${{ steps.env.outputs.installer_exe }}"
        ./google-book-scraper-0.4.0-windows-arm64-installer.exe /Silent /LOG=log.txt
        ls
        cat ./log.txt
        gbscraper --version
        echo $(gbscraper --version)
        rm google-book-scraper-0.4.0-windows-arm64-installer.exe

    - name: Checkout
      uses: actions/checkout@v6

    - name: Set Rust flags
      run: echo "RUSTFLAGS=-Ctarget-feature=+crt-static" >> $Env:GITHUB_ENV

    - name: Build
      run: |

        # Build
        rustup target add ${{ matrix.platform.target }}
        cargo build --release --target ${{ matrix.platform.target }}
        
        # Move/copy files needed for release
        mkdir publish
        cp README.md publish
        cp LICENSE-APACHE publish
        cp LICENSE-MIT publish
        cp attribution.txt publish
        mv target/${{ matrix.platform.target }}/release/gbscraper.exe publish

    - name: Create release files
      run: |
        cd publish
        7z a "../$Env:PORTABLE_ZIP" *
        cp ../pkg/winget/installer.iss .
        iscc /O".." /F"$Env:INSTALLER_BASE" installer.iss
        cd ..
        ls

    - name: Upload portable artifact
      uses: actions/upload-artifact@v7
      with:
        path: ${{ matrix.platform.filename }}-portable.zip
        archive: false

    - name: Upload installer artifact
      uses: actions/upload-artifact@v7
      with:
        path: ${{ matrix.platform.filename }}-installer.exe
        archive: false

    - name: Test built installer
      run: |

        echo "don't run this workflow unless winget publish fails and you need to rebuild the installers"

        # gh release delete-asset $env:TAG $env:INSTALLER_EXE -y
        # gh release delete-asset $Env:TAG $Env:PORTABLE_ZIP -y

        ## build installer from existingrelease asset
        # gh release download $Env:TAG -p $Env:PORTABLE_ZIP
        # 7z x $Env:PORTABLE_ZIP
        # cp ../pkg/winget/installer.iss .
        # iscc /O"." /F"$Env:INSTALLER_BASE" installer.iss

        # gh release upload $Env:TAG $Env:INSTALLER_EXE
        # gh release upload $Env:TAG $Env:PORTABLE_ZIP

        # test installer
        ./google-book-scraper-0.4.0-windows-arm64-installer.exe /VerySilent /LOG=./log.txt
        ls
        cat ./log.txt
        gbscraper --version
        echo $(gbscraper --version)