name: Version (test)
description: Version (test)

on:
  release:
    types: [published]
  push:
    branches: [ "action_release_test" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  
jobs:

  run:
    name: Action test
    runs-on: windows-latest
    steps:
      - id: lastversion
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
      - name: Print latest version
        run: |
          echo "latest version from action: ${{ steps.lastversion.outputs.release  }}"
      - name: output
        env:
            VERSION: ${{ github.event.release.tag_name || steps.lastversion.outputs.release  }}
        run: |
          echo "latest version: $env:VERSION"