name: Release

on:
  release:
    types: [published]
    
permissions:
  contents: write
  
env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}
  VERSION: ${{ github.event.release.tag_name }}

jobs:

  build:
    name: Build and upload binaries
    strategy:
      matrix:
        platform: 
          - name: Windows-x86_64
            runs_on: windows-latest
            target: x86_64-pc-windows-msvc
            bin: gbscraper.exe
            filename: "google-book-scraper-$($env:VERSION.Substring(1))-windows-amd64.zip"
          - name: Windows-i686
            runs_on: windows-latest
            target: i686-pc-windows-msvc
            bin: gbscraper.exe
            filename: "google-book-scraper-$($env:VERSION.Substring(1))-windows-i686.zip"
          - name: Windows-aarch64
            runs_on: windows-latest
            target: aarch64-pc-windows-msvc
            bin: gbscraper.exe
            filename: "google-book-scraper-$($env:VERSION.Substring(1))-windows-arm64.zip"
          - name: macOS-x86_64
            runs_on: macOS-latest
            target: x86_64-apple-darwin
            bin: gbscraper
            filename: "google-book-scraper-${VERSION#v}-darwin-amd64.tar.gz"
          - name: macOS-aarch64
            runs_on: macOS-latest
            target: aarch64-apple-darwin
            bin: gbscraper
            filename: "google-book-scraper-${VERSION#v}-darwin-arm64.tar.gz"
          - name: Linux-x86_64
            runs_on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: gbscraper
            filename: "google-book-scraper-${VERSION#v}-linux-amd64.tar.gz"
          - name: Linux-i686
            runs_on: ubuntu-latest
            target: i686-unknown-linux-gnu
            bin: gbscraper
            filename:  "google-book-scraper-$VERSION-linux-i686.tar.gz"
          - name: Linux-aarch64
            runs_on: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            bin: gbscraper
            filename: "google-book-scraper-${VERSION#v}-linux-arm64.tar.gz"
    runs-on: ${{ matrix.platform.runs_on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Configure
      if: matrix.platform.name == 'Linux-i686'
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install gcc-multilib g++-multilib libssl-dev:i386 pkg-config 
        echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
        echo "OPENSSL_LIB_DIR=/usr/lib/i386-linux-gnu/" >> $GITHUB_ENV
        echo "OPENSSL_INCLUDE_DIR=/usr/include/openssl/" >> $GITHUB_ENV
    - name: Build - ${{ matrix.platform.name }}
      run: |
        rustup target add ${{ matrix.platform.target }}
        cargo build --release --target ${{ matrix.platform.target }}
    - name: Archive prep
      run: |
        mkdir publish
        cp README.md publish
        cp LICENSE-APACHE publish
        cp LICENSE-MIT publish
        cp attribution.txt publish
        mv target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }} publish
    - name: Archive (.zip)
      if: matrix.platform.runs_on == 'windows-latest'
      run: |
        cd publish
        7z a ../${{ matrix.platform.filename }} *
    - name: Archive (.tar.gz)
      if: matrix.platform.runs_on != 'windows-latest'
      run: |
        cd publish
        tar cvzf ../${{ matrix.platform.filename }} *
    - name: Release
      run:
        gh release upload ${{ github.event.release.tag_name }} ${{ matrix.platform.filename }}

  publish_crate:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    # environment: release  # Optional: for enhanced security
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v6
    - uses: rust-lang/crates-io-auth-action@v1
      id: auth
    - run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  publis_homebrew:
    runs-on: ubuntu-latest
    needs: build
    name: Publish to brew tap
    steps:
      - name: Release project to Homebrew tap
        uses: Justintime50/homebrew-releaser@v3
        with:
          homebrew_owner: shloop
          homebrew_tap: homebrew-tap
          github_token: ${{ secrets.TAP_TOKEN }}
          target_darwin_amd64: true
          target_darwin_arm64: true
          target_linux_amd64: true
          target_linux_arm64: true
          install: 'bin.install "gbscraper"'
          update_readme_table: true