name: Build_TEST

on:
  push:
  pull_request:
    branches: [ "brew_test" ]
  
env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}
  VERSION: ${{ github.ref_name }}
  # VERSION: ${{ github.event.release.tag_name }}

jobs:

  build:
    name: Build binaries and upload to release
    strategy:
      matrix:
        platform: 
          - name: Windows-x86_64
            runs_on: windows-latest
            target: x86_64-pc-windows-msvc
            bin: gbscraper.exe
            filenameA: "google-book-scraper-$('${{ github.ref_name }}'.Substring(1))-windows-amd64.zip"
            filenameB: "google-book-scraper-$($VERSION.Substring(1))-windows-amd64.zip"
    runs-on: ${{ matrix.platform.runs_on }}
    steps:
    - name: Print
      run: |
        echo "a $VERSION"
        echo "b $env.VERSION"
        echo "c $env:VERSION"
        echo "d ${{ matrix.platform.filenameA }}"
        echo "e ${{ matrix.platform.filenameB }}"