name: Test

on: 
  push:
    # Don't run tests when pushing to branches that start with "action_". 
    # These are used for testing other workflows.
    branches-ignore: [ "action_*" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Run tests
      run: cargo test --verbose
