name: Test

on: 
  push:
    # Don't run tests on changes to license files, documentation, or workflow files
    paths-ignore:
      - "*.md"
      - "*.yml"
      - "*.txt"
      - "LICENSE*"
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
