name: Update installers

on:
  push:
    branches: [ "winget_troubleshooting" ]

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}
  VERSION: 0.4.0

permissions:
  contents: write

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set version
        id: set_version
        run: |
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  build_installers:
    name: Rebuild installers
    needs: setup
    strategy:
      matrix:
        platform: 
          - name: Windows-i686
            arch: x86compatible
            target: i686-pc-windows-msvc
            filename: google-book-scraper-${{ needs.setup.outputs.version }}-windows-x86
          - name: Windows-x86_64
            arch: x64compatible
            target: x86_64-pc-windows-msvc
            filename: google-book-scraper-${{ needs.setup.outputs.version }}-windows-x64
          - name: Windows-aarch64
            arch: arm64
            target: aarch64-pc-windows-msvc
            filename: google-book-scraper-${{ needs.setup.outputs.version }}-windows-arm64
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Work
      env:
        TAG: v${{ needs.setup.outputs.version }}
        INSTALLER_BASE: ${{ matrix.platform.filename }}-installer
        INSTALLER_EXE: ${{ matrix.platform.filename }}-installer.exe
        PORTABLE_ZIP: ${{ matrix.platform.filename }}-portable.zip
      run: |

        mkdir tmp
        cd tmp

        gh release delete-asset $env:TAG $env:INSTALLER_EXE -y

        gh release download $env:TAG $env:PORTABLE_ZIP -y

        7z x $env:PORTABLE_ZIP

        cp ../pkg/winget/installer.iss .

        iscc /O"." /F"$env:INSTALLER_BASE" installer.iss

        gh release upload $env:TAG $env:INSTALLER_EXE

