name: Update installers

on:
  push:
    branches: [ "winget_troubleshooting" ]

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}
  VERSION: 0.4.0

permissions:
  contents: write

jobs:

  build_installers:
    name: Rebuild installers
    strategy:
      matrix:
        platform: 
          - name: Windows-i686
            arch: x86compatible
            target: i686-pc-windows-msvc
            filename: google-book-scraper-$env:VERSION-windows-x86
          - name: Windows-x86_64
            arch: x64compatible
            target: x86_64-pc-windows-msvc
            filename: google-book-scraper-$env:VERSION-windows-x64
          - name: Windows-aarch64
            arch: arm64
            target: aarch64-pc-windows-msvc
            filename: google-book-scraper-$env:VERSION-windows-arm64
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Work
      env:
        TAG: v$env:VERSION
        INSTALLER_BASE: ${{ matrix.platform.filename }}-installer
        INSTALLER_EXE: ${{ matrix.platform.filename }}-installer.exe
        PORTABLE_ZIP: ${{ matrix.platform.filename }}-portable.zip
      run: |
        gh release delete-asset $env:TAG $env:INSTALLER_EXE -y

        gh release download $env:TAG $env:PORTABLE_ZIP -y

        7z e $env:PORTABLE_ZIP

        cp pkg/winget/installer.iss .

        iscc /O"." /F"$env:INSTALLER_BASE" pkg/winget/installer.iss

        gh release upload $env:TAG $env:INSTALLER_EXE

