name: Publish to WinGet

on:
  push:
    branches: [ "winget_upload______" ]

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write

jobs:

  build_installers:
    name: Build installers
    strategy:
      matrix:
        platform: 
          - name: Windows-x86_64
            arch: x64compatible
            target: x86_64-pc-windows-msvc
            filename: google-book-scraper-0.3.8-windows-x64-installer
          - name: Windows-i686
            arch: x86compatible
            target: i686-pc-windows-msvc
            filename: google-book-scraper-0.3.8-windows-x86-installer
          - name: Windows-aarch64
            arch: arm64
            target: aarch64-pc-windows-msvc
            filename: google-book-scraper-0.3.8-windows-arm64-installer
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Build - ${{ matrix.platform.name }}
      env:
        RUSTFLAGS: -C target-feature=+crt-static
      run: |
        rustup target add ${{ matrix.platform.target }}
        cargo build --release --target ${{ matrix.platform.target }}
    - name: Build installer - ${{ matrix.platform.name }}
      env: 
        # VERSION: "{{ github.event.release.tag_name }}".Substring(1)
        VERSION: 0.3.8
        ARCH: ${{ matrix.platform.arch }}
      run: |
        cp target/${{ matrix.platform.target }}/release/gbscraper.exe .
        iscc /O"." /F"${{ matrix.platform.filename }}" installer.iss
    - name: Release
      run: |
        gh release upload v0.3.8 ${{ matrix.platform.filename }}.exe

